name: android-capacitor

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-android:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js and export static site
        run: |
          npm run build
          npx next export

      - name: Install Capacitor CLI
        run: npm i -D @capacitor/cli

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses and install build tools
        shell: bash
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Add Android platform (if not present) and sync
        run: |
          npx cap add android || echo "Android platform already exists"
          npx cap sync android

      - name: Build debug APK
        run: .\android\gradlew.bat -p .\android assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
